apiVersion: v1
kind: Service
metadata:
  name: orders-postgresql-service
spec:
  selector:
    app: orders-postgresql
  type: ClusterIP
  ports:
    - name: orders-postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
