apiVersion: v1
kind: Service
metadata:
  name: cache-redis-service
spec:
  selector:
    app: cache-redis
  type: ClusterIP
  ports:
    - name: cache-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: cache-redis-service
spec:
  selector:
    app: cache-redis
  type: NodePort
  ports:
    - name: cache-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30005