apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-redis
  template:
    metadata:
      labels:
        app: cache-redis
    spec:
      containers:
        - name: cache-redis
          image: "redis:latest"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "800m"