apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - name: gateway
      protocol: TCP
      port: 3000
      targetPort: 3000
