apiVersion: v1
kind: Service
metadata:
  name: payments-mongodb-service
spec:
  selector:
    app: payments-mongodb
  type: ClusterIP
  ports:
    - name: payments-mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: payments-mongo-service-node-port
spec:
  selector:
    app: payments-mongo
  type: NodePort
  ports:
    - name: payments-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30006
