apiVersion: v1
kind: Service
metadata:
  name: products-mysql-service
spec:
  selector:
    app: products-mysql
  type: ClusterIP
  ports:
    - name: products-mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
