apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-mysql
  template:
    metadata:
      labels:
        app: products-mysql
    spec:
      # automountServiceAccountToken: false
      containers:
        - name: products-mysql
          image: "mysql:latest"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "products"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"
